---
local:
  user: michaelfox # local username
  group: admin # local group
  server: localhost
  deploy_dir: # N/A
  solr_dir: "~/solr-5.3.0/server/solr" # path to your solr server dir
  local_code_dir: "~/Sites/blake/archive" # path to the local install of the code base
  webdata_dir: # N/A
  restart: # N/A
qa:
  user:
  group:
  server:
  deploy_dir:
  solr_dir:
  webdata_dir:
  restart:
prod:
  user:
  group:
  server:
  deploy_dir:
  solr_dir:
  webdata_dir:
  restart:
